# Generated by Django 5.1.5 on 2025-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIK', models.CharField(max_length=100, unique=True)),
                ('nama_penumpang', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('telp', models.CharField(max_length=20)),
            ],
        ),
    ]
