# Generated by Django 5.1.5 on 2025-02-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kereta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kereta', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('kelas', models.CharField(max_length=50)),
            ],
        ),
    ]
