# Generated by Django 5.1.5 on 2025-02-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggan',
            name='NIK',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
