# Generated by Django 5.1.5 on 2025-02-07 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detail_pembelian', '0001_initial'),
        ('kursi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailpembelian',
            name='kursi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_pembelians', to='kursi.kursi'),
        ),
    ]
