# Generated by Django 5.1.5 on 2025-02-07 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerbong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kursi', models.CharField(max_length=10)),
                ('gerbong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kursis', to='gerbong.gerbong')),
            ],
        ),
    ]
