# Generated by Django 5.1.5 on 2025-02-07 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kereta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asal_keberangkatan', models.CharField(max_length=100)),
                ('tujuan_keberangkatan', models.CharField(max_length=100)),
                ('tanggal_berangkat', models.DateTimeField()),
                ('tanggal_kedatangan', models.DateTimeField()),
                ('harga', models.FloatField()),
                ('kereta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jadwals', to='kereta.kereta')),
            ],
        ),
    ]
